/**
 * RoalerCoster
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: max@muster.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Design } from './design';
import { Location } from './location';
import { Status } from './status';
import { Typ } from './typ';

/**
 * A roaler coaster
 */
export interface Coaster { 
    id: number;
    /**
     * The name of the roaler coaster
     */
    name: string;
    location?: Location;
    typ?: Typ;
    design?: Design;
    status?: Status;
    /**
     * The opening date of this roaler coaster
     */
    openedDate?: string;
}