/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * RWEI was ist eine CodePunkt
 */
export interface CodePunkt { 
    /**
     * RWEI ist das irgend eine db id?
     */
    id: number;
    station: string;
    gleis: string;
    /**
     * RWEI ginge das nicht als enum? Oder was bedeutet welche nummer?
     */
    typ: string;
}