/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * RWEI was ist eine ElzMessage
 */
export interface ElzMessage {
    /**
     * Iltis zelle
     */
    zelle: string;
    /**
     * RWEI was ist das für eine Zeit?
     */
    timestamp: Date;
    /**
     * RWEI was ist hier zu erwarten? gibt es eine art ENUM?
     */
    elementTyp: string;
    /**
     * RWEI was ist hier zu erwarten? gibt es eine art ENUM?
     */
    station: string;
    /**
     * RWEI was ist hier zu erwarten?
     */
    elementName: string;
    statusBitWert: boolean;
    /**
     * RWEI was ist das für eine Zeit und wie unterscheidet diese sich von \"timestamp\"
     */
    dateTime: any;
}
