/**
 * RoalerCoster
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: max@muster.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HavingPK } from './havingPK';
import { Pageable } from './pageable';
import { Sort } from './sort';

export interface PageHavingPK { 
    totalElements?: number;
    totalPages?: number;
    number?: number;
    size?: number;
    content?: Array<HavingPK>;
    sort?: Sort;
    numberOfElements?: number;
    first?: boolean;
    pageable?: Pageable;
    last?: boolean;
    empty?: boolean;
}