/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * RWEI was ist eine TzdeTime, Ich finde nirgends ein sample.
 */
export interface TzdeTime { 
    type: string;
    time: string;
    source: string;
    typ: string;
}