/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodePunkt } from './codePunkt';
import { TzdeDiskri } from './tzdeDiskri';
import { TzdeTime } from './tzdeTime';

export interface TzdeGleisfeld { 
    codePunkt: CodePunkt;
    /**
     * RWEI was ist das? Gibt es da ein ENUM?
     */
    type: string;
    /**
     * RWEI was ist das? Gibt es da ein ENUM?
     */
    richtung: string;
    alternierend: boolean;
    times?: Array<TzdeTime>;
    diskris?: Array<TzdeDiskri>;
    inTimetable: boolean;
}