/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TzdeGleisfeld } from './tzdeGleisfeld';
import { ZugIdentifikation } from './zugIdentifikation';

/**
 * RWEI was ist eine TzdeMessage
 */
export interface TzdeMessage {
    /**
     * Iltis zelle
     */
    zelle: string;
    /**
     * RWEI was ist das für eine Zeit?
     */
    timestamp: Date;
    /**
     * RWEI wozu ist das? Was kann man damit anfangen?
     */
    uuid: string;
    /**
     * RWEI kann man das weiter beschreiben?
     */
    status: TzdeMessage.StatusEnum;
    /**
     * RWEI kann man das weiter beschreiben?
     */
    halbtagAktivierung: boolean;
    /**
     * RWEI was ist das für eine Zeit?
     */
    htaDatum: any;
    /**
     * RWEI was ist das? Wieso string und nicht int?
     */
    htaNummer: string;
    zugIdentifikation: ZugIdentifikation;
    gleisfelder: Array<TzdeGleisfeld>;
    /**
     * RWEI wozu braucht man das?
     */
    referenzId: string;
    /**
     * RWEI wozu braucht man das?
     */
    topologieId: string;
    /**
     * RWEI wozu braucht man das?
     */
    regelsetId: number;
    impliziteLoeschung: boolean;
    iltisVerkehrsDatum: string;
    iltisVerkehrsZeit?: string;
    /**
     * RWEI was ist das?
     */
    grunddatenId: number;
}
export namespace TzdeMessage {
    export type StatusEnum = 'CREATE' | 'UNKONWN_PTS_B' | 'UNKONWN_PTS_C' | 'UNKONWN_PTS_D' | 'UNKONWN_PTS_E' | 'UPDATE' | 'DELETE' | 'UNKONWN';
    export const StatusEnum = {
        CREATE: 'CREATE' as StatusEnum,
        UNKONWNPTSB: 'UNKONWN_PTS_B' as StatusEnum,
        UNKONWNPTSC: 'UNKONWN_PTS_C' as StatusEnum,
        UNKONWNPTSD: 'UNKONWN_PTS_D' as StatusEnum,
        UNKONWNPTSE: 'UNKONWN_PTS_E' as StatusEnum,
        UPDATE: 'UPDATE' as StatusEnum,
        DELETE: 'DELETE' as StatusEnum,
        UNKONWN: 'UNKONWN' as StatusEnum
    };
}
