/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ZugIdentifikation } from './zugIdentifikation';

/**
 * 0f1e6741-9d39-4c28-b24e-fcc3d2f01be2
 */
export interface ZnvMessage { 
    /**
     * Iltis zelle
     */
    zelle: string;
    /**
     * RWEI was ist das für eine Zeit?
     */
    timestamp: Date;
    /**
     * RWEI wozu ist das? Was kann man damit anfangen?
     */
    uuid: string;
    typ: ZnvMessage.TypEnum;
    /**
     * RWEI was ist das?
     */
    skalar: boolean;
    bisStation: string;
    bisGleisName: string;
    bisZugIdentifikation: ZugIdentifikation;
    vonStation: string;
    vonGleisName: string;
    vonZugIdentifikation: ZugIdentifikation;
    /**
     * RWEI was ist das? Geht das auch als ENUM?
     */
    znQuelle: string;
    /**
     * RWEI was ist das? Kannst du bitte ein example liefern.
     */
    lzQuelle?: string;
    /**
     * RWEI was ist das? Kannst du bitte ein example liefern.
     */
    gaIndikator?: string;
}
export namespace ZnvMessage {
    export type TypEnum = 'ORT' | 'WEG' | 'LOESCH' | 'UNDEFINIERT';
    export const TypEnum = {
        ORT: 'ORT' as TypEnum,
        WEG: 'WEG' as TypEnum,
        LOESCH: 'LOESCH' as TypEnum,
        UNDEFINIERT: 'UNDEFINIERT' as TypEnum
    };
}