spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: never
    platform: postgres
    url: "jdbc:postgresql://db-postgresql-fra1-39545-do-user-2658320-0.b.db.ondigitalocean.com:25060/db1"
    username: user
    password: mtivwpb48y98e91v
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-adhggyp0.eu.auth0.com/
        audience: http://localhost:4200


restapi:
  time-service:
    uri: http://localhost:8039
    audience: http://localhost:4200
    oauth2-client:
      client-id: qMspHej5iXd5h4ukMiMlcJaRG5LUaBVt
      client-secret: WyoZEApH0D3Iwhqyin5McN-QHf0ch0vZ_GNAWeOvf5VnRzXEli8projDyKAWpUnM
      access-token-uri: https://dev-adhggyp0.eu.auth0.com/oauth/token
      client-authentication-scheme: form

server:
  port: 8038

logging:
  level:
    root: INFO
    com:
      example: ${LOG_LEVEL:INFO}
    org:
      springframework:
        web: ${LOG_LEVEL:INFO}
        client: DEBUG
        http:
          client: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always