spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: never
    platform: postgres
    url: "jdbc:postgresql://db-postgresql-fra1-39545-do-user-2658320-0.a.db.ondigitalocean.com:25060/db1"
    username: user
    password: ttay3lh08nfddlx0


server:
  port: 8038
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always